# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd.setAutoFillBackground(False)
        self.lcd.setStyleSheet("background-color: rgb(200, 230, 234);")
        self.lcd.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcd.setLineWidth(2)
        self.lcd.setSmallDecimalPoint(True)
        self.lcd.setNumDigits(11)
        self.lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd.setObjectName("lcd")
        self.verticalLayout.addWidget(self.lcd)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.minus.setFont(font)
        self.minus.setAutoFillBackground(False)
        self.minus.setObjectName("minus")
        self.gridLayout_2.addWidget(self.minus, 1, 3, 1, 1)
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.multiply.setFont(font)
        self.multiply.setAutoFillBackground(False)
        self.multiply.setObjectName("multiply")
        self.gridLayout_2.addWidget(self.multiply, 2, 3, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setAutoFillBackground(False)
        self.b2.setObjectName("b2")
        self.gridLayout_2.addWidget(self.b2, 3, 1, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setAutoFillBackground(False)
        self.b1.setObjectName("b1")
        self.gridLayout_2.addWidget(self.b1, 3, 0, 1, 1)
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setAutoFillBackground(False)
        self.b5.setObjectName("b5")
        self.gridLayout_2.addWidget(self.b5, 2, 1, 1, 1)
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setAutoFillBackground(False)
        self.b3.setObjectName("b3")
        self.gridLayout_2.addWidget(self.b3, 3, 2, 1, 1)
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setAutoFillBackground(False)
        self.b6.setObjectName("b6")
        self.gridLayout_2.addWidget(self.b6, 2, 2, 1, 1)
        self.b9 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setAutoFillBackground(False)
        self.b9.setObjectName("b9")
        self.gridLayout_2.addWidget(self.b9, 1, 2, 1, 1)
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setAutoFillBackground(False)
        self.b4.setObjectName("b4")
        self.gridLayout_2.addWidget(self.b4, 2, 0, 1, 1)
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.divide.setFont(font)
        self.divide.setAutoFillBackground(False)
        self.divide.setObjectName("divide")
        self.gridLayout_2.addWidget(self.divide, 3, 3, 1, 1)
        self.b8 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setAutoFillBackground(False)
        self.b8.setObjectName("b8")
        self.gridLayout_2.addWidget(self.b8, 1, 1, 1, 1)
        self.b7 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setAutoFillBackground(False)
        self.b7.setObjectName("b7")
        self.gridLayout_2.addWidget(self.b7, 1, 0, 1, 1)
        self.startbracket = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.startbracket.setFont(font)
        self.startbracket.setObjectName("startbracket")
        self.gridLayout_2.addWidget(self.startbracket, 0, 1, 1, 1)
        self.endbracket = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.endbracket.setFont(font)
        self.endbracket.setObjectName("endbracket")
        self.gridLayout_2.addWidget(self.endbracket, 0, 2, 1, 1)
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.plus.setFont(font)
        self.plus.setAutoFillBackground(False)
        self.plus.setObjectName("plus")
        self.gridLayout_2.addWidget(self.plus, 0, 3, 1, 1)
        self.scientificWidget = QtWidgets.QWidget(self.centralwidget)
        self.scientificWidget.setObjectName("scientificWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.scientificWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pi = QtWidgets.QPushButton(self.scientificWidget)
        self.pi.setObjectName("pi")
        self.gridLayout.addWidget(self.pi, 6, 0, 1, 1)
        self.cuberoot = QtWidgets.QPushButton(self.scientificWidget)
        self.cuberoot.setObjectName("cuberoot")
        self.gridLayout.addWidget(self.cuberoot, 5, 0, 1, 1)
        self.cos = QtWidgets.QPushButton(self.scientificWidget)
        self.cos.setObjectName("cos")
        self.gridLayout.addWidget(self.cos, 1, 0, 1, 1)
        self.tan = QtWidgets.QPushButton(self.scientificWidget)
        self.tan.setObjectName("tan")
        self.gridLayout.addWidget(self.tan, 2, 0, 1, 1)
        self.log = QtWidgets.QPushButton(self.scientificWidget)
        self.log.setObjectName("log")
        self.gridLayout.addWidget(self.log, 3, 0, 1, 1)
        self.sin = QtWidgets.QPushButton(self.scientificWidget)
        self.sin.setObjectName("sin")
        self.gridLayout.addWidget(self.sin, 0, 0, 1, 1)
        self.ln = QtWidgets.QPushButton(self.scientificWidget)
        self.ln.setObjectName("ln")
        self.gridLayout.addWidget(self.ln, 4, 0, 1, 1)
        self.asin = QtWidgets.QPushButton(self.scientificWidget)
        self.asin.setObjectName("asin")
        self.gridLayout.addWidget(self.asin, 0, 1, 1, 1)
        self.acos = QtWidgets.QPushButton(self.scientificWidget)
        self.acos.setObjectName("acos")
        self.gridLayout.addWidget(self.acos, 1, 1, 1, 1)
        self.atan = QtWidgets.QPushButton(self.scientificWidget)
        self.atan.setObjectName("atan")
        self.gridLayout.addWidget(self.atan, 2, 1, 1, 1)
        self.antilog = QtWidgets.QPushButton(self.scientificWidget)
        self.antilog.setObjectName("antilog")
        self.gridLayout.addWidget(self.antilog, 3, 1, 1, 1)
        self.antiln = QtWidgets.QPushButton(self.scientificWidget)
        self.antiln.setObjectName("antiln")
        self.gridLayout.addWidget(self.antiln, 4, 1, 1, 1)
        self.power = QtWidgets.QPushButton(self.scientificWidget)
        self.power.setObjectName("power")
        self.gridLayout.addWidget(self.power, 5, 1, 1, 1)
        self.e = QtWidgets.QPushButton(self.scientificWidget)
        self.e.setObjectName("e")
        self.gridLayout.addWidget(self.e, 6, 1, 1, 1)
        self.gridLayout_2.addWidget(self.scientificWidget, 0, 4, 5, 1)
        self.clrAll = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.clrAll.setFont(font)
        self.clrAll.setObjectName("clrAll")
        self.gridLayout_2.addWidget(self.clrAll, 0, 0, 1, 1)
        self.equals = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.equals.setFont(font)
        self.equals.setObjectName("equals")
        self.gridLayout_2.addWidget(self.equals, 4, 3, 1, 1)
        self.point = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.point.setFont(font)
        self.point.setAutoFillBackground(False)
        self.point.setObjectName("point")
        self.gridLayout_2.addWidget(self.point, 4, 2, 1, 1)
        self.b0 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setAutoFillBackground(False)
        self.b0.setObjectName("b0")
        self.gridLayout_2.addWidget(self.b0, 4, 1, 1, 1)
        self.root = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.root.setFont(font)
        self.root.setObjectName("root")
        self.gridLayout_2.addWidget(self.root, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 502, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMode = QtWidgets.QMenu(self.menuBar)
        self.menuMode.setObjectName("menuMode")
        self.menuAngle = QtWidgets.QMenu(self.menuBar)
        self.menuAngle.setObjectName("menuAngle")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSimple = QtWidgets.QAction(MainWindow)
        self.actionSimple.setCheckable(True)
        self.actionSimple.setChecked(True)
        self.actionSimple.setObjectName("actionSimple")
        self.actionScientific = QtWidgets.QAction(MainWindow)
        self.actionScientific.setCheckable(True)
        self.actionScientific.setObjectName("actionScientific")
        self.actionDegree = QtWidgets.QAction(MainWindow)
        self.actionDegree.setCheckable(True)
        self.actionDegree.setChecked(True)
        self.actionDegree.setObjectName("actionDegree")
        self.actionRadian = QtWidgets.QAction(MainWindow)
        self.actionRadian.setCheckable(True)
        self.actionRadian.setObjectName("actionRadian")
        self.menuMode.addAction(self.actionSimple)
        self.menuMode.addAction(self.actionScientific)
        self.menuAngle.addAction(self.actionDegree)
        self.menuAngle.addAction(self.actionRadian)
        self.menuBar.addAction(self.menuMode.menuAction())
        self.menuBar.addAction(self.menuAngle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qalculator"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.minus.setShortcut(_translate("MainWindow", "-"))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.multiply.setShortcut(_translate("MainWindow", "*"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.b2.setShortcut(_translate("MainWindow", "2"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b1.setShortcut(_translate("MainWindow", "1"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b5.setShortcut(_translate("MainWindow", "5"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b3.setShortcut(_translate("MainWindow", "3"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b6.setShortcut(_translate("MainWindow", "6"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b9.setShortcut(_translate("MainWindow", "9"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b4.setShortcut(_translate("MainWindow", "4"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.divide.setShortcut(_translate("MainWindow", "/"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.b8.setShortcut(_translate("MainWindow", "8"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.b7.setShortcut(_translate("MainWindow", "7"))
        self.startbracket.setText(_translate("MainWindow", "("))
        self.startbracket.setShortcut(_translate("MainWindow", "("))
        self.endbracket.setText(_translate("MainWindow", ")"))
        self.endbracket.setShortcut(_translate("MainWindow", ")"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.plus.setShortcut(_translate("MainWindow", "+"))
        self.pi.setText(_translate("MainWindow", "π"))
        self.cuberoot.setText(_translate("MainWindow", "∛"))
        self.cos.setText(_translate("MainWindow", "cos"))
        self.tan.setText(_translate("MainWindow", "tan"))
        self.log.setText(_translate("MainWindow", "log"))
        self.sin.setText(_translate("MainWindow", "sin"))
        self.ln.setText(_translate("MainWindow", "ln"))
        self.asin.setText(_translate("MainWindow", "sin⁻¹"))
        self.acos.setText(_translate("MainWindow", "cos⁻¹"))
        self.atan.setText(_translate("MainWindow", "tan⁻¹"))
        self.antilog.setText(_translate("MainWindow", "10^x"))
        self.antiln.setText(_translate("MainWindow", "e^x"))
        self.power.setText(_translate("MainWindow", "^"))
        self.e.setText(_translate("MainWindow", "e"))
        self.clrAll.setText(_translate("MainWindow", "C"))
        self.clrAll.setShortcut(_translate("MainWindow", "Del"))
        self.equals.setText(_translate("MainWindow", "="))
        self.equals.setShortcut(_translate("MainWindow", "="))
        self.point.setText(_translate("MainWindow", "."))
        self.point.setShortcut(_translate("MainWindow", "."))
        self.b0.setText(_translate("MainWindow", "0"))
        self.b0.setShortcut(_translate("MainWindow", "0"))
        self.root.setText(_translate("MainWindow", "√x"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.menuAngle.setTitle(_translate("MainWindow", "Angle"))
        self.actionSimple.setText(_translate("MainWindow", "Simple"))
        self.actionScientific.setText(_translate("MainWindow", "Scientific"))
        self.actionDegree.setText(_translate("MainWindow", "Degree"))
        self.actionRadian.setText(_translate("MainWindow", "Radian"))

